version: '3'

services:
  node:
    build: 
      context: .
    image: leonardoestevam/fullcycle_docker_exercicio_2:2.0
    container_name: node-app
    volumes:
      - ./src:/usr/src/app
    ports:
      - "80:3000"
    networks:
      - nodenet
    tty: true

  database:
    image: mysql:5.7
    container_name: mysql-db
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
      
networks:
  nodenet:
    driver: bridge